//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.08 at 12:11:29 PM IST 
//


package com.metlife.business.service.premiumservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.metlife.webservices.Account;
import com.metlife.webservices.Premium;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PremiumDetails" type="{http://webservices.samples.blog.com}Account"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "premiumDetails"
})
@XmlRootElement(name = "PremiumDetailsResponse")
public class PremiumDetailsResponse {

    @XmlElement(name = "PremiumDetails", required = true)
    protected Premium premiumDetails;

    /**
     * Gets the value of the premiumDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Premium getPremiumDetails() {
        return premiumDetails;
    }

    /**
     * Sets the value of the premiumDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setPremiumDetails(Premium value) {
        this.premiumDetails = value;
    }

}
