
package com.metlife.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PremiumDetailsService", targetNamespace = "http://com/metlife/business/service/accountservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
	com.metlife.webservice.client.ObjectFactory.class
})
public interface PremiumDetailsService {


    /**
     * 
     * @param premiumDetailsRequest
     * @return
     *     returns com.metlife.business.service.accountservice.PremiumDetailsResponse
     */
    @WebMethod(operationName = "PremiumDetails")
    @WebResult(name = "PremiumDetailsResponse", targetNamespace = "http://com/metlife/business/service/accountservice", partName = "PremiumDetailsResponse")
    public PremiumDetailsResponse premiumDetails(
        @WebParam(name = "PremiumDetailsRequest", targetNamespace = "http://com/metlife/business/service/accountservice", partName = "PremiumDetailsRequest")
        PremiumDetailsRequest premiumDetailsRequest);

}
