
package com.metlife.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PremiumDetailsServices", targetNamespace = "http://com/metlife/business/service/accountservice", wsdlLocation = "http://localhost:9080/spring-webservices-sample/endpoints/PremiumDetailsService.wsdl")
public class PremiumDetailsServices
    extends Service
{

    private final static URL PREMIUMDETAILSSERVICES_WSDL_LOCATION;
    private final static WebServiceException PREMIUMDETAILSSERVICES_EXCEPTION;
    private final static QName PREMIUMDETAILSSERVICES_QNAME = new QName("http://com/metlife/business/service/accountservice", "PremiumDetailsServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/spring-webservices-sample/endpoints/PremiumDetailsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREMIUMDETAILSSERVICES_WSDL_LOCATION = url;
        PREMIUMDETAILSSERVICES_EXCEPTION = e;
    }

    public PremiumDetailsServices() {
        super(__getWsdlLocation(), PREMIUMDETAILSSERVICES_QNAME);
    }

    public PremiumDetailsServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREMIUMDETAILSSERVICES_QNAME, features);
    }

    public PremiumDetailsServices(URL wsdlLocation) {
        super(wsdlLocation, PREMIUMDETAILSSERVICES_QNAME);
    }

    public PremiumDetailsServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREMIUMDETAILSSERVICES_QNAME, features);
    }

    public PremiumDetailsServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PremiumDetailsServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PremiumDetailsService
     */
    @WebEndpoint(name = "PremiumDetailsServiceSoap11")
    public PremiumDetailsService getPremiumDetailsServiceSoap11() {
        return super.getPort(new QName("http://com/metlife/business/service/accountservice", "PremiumDetailsServiceSoap11"), PremiumDetailsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PremiumDetailsService
     */
    @WebEndpoint(name = "PremiumDetailsServiceSoap11")
    public PremiumDetailsService getPremiumDetailsServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://com/metlife/business/service/accountservice", "PremiumDetailsServiceSoap11"), PremiumDetailsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREMIUMDETAILSSERVICES_EXCEPTION!= null) {
            throw PREMIUMDETAILSSERVICES_EXCEPTION;
        }
        return PREMIUMDETAILSSERVICES_WSDL_LOCATION;
    }

}
